#!/usr/bin/python

#################################################################################
# @PROJECT: PhonTA - Phonetic Transcription Assistant                           #
# @VERSION:                                                                     #
# @AUTHOR: Benjamin Meyers                                                      #
# @EMAIL: ben@lionlogic.org                                                     #
# @LICENSE: MIT                                                                 #
#################################################################################

##### IMPORTS ###################################################################
import sys
from dict.util import upgrade_cmudict, translate, add_to_cmudict

##### GLOBALS ###################################################################
commands = {"upgrade":upgrade_cmudict,	"translate":translate,	"add":add_to_cmudict}

def display_help_message():
	print("USAGE: phonta <command> <options>")
	print("\t--help,  -h\tDisplay this message.")
	print("\t--info,  -i\tDiplay program information.")
	print("\t--usage, -u\tDisplay usage instructions.")

def display_info_message():
	print("\n")
	print("#################################################")
	print("# PhonTA - Phonetic Transcription Assistant\t#")
	print("#\t\t\t\t\t\t#")
	print("# Copyright (c) 2016,   Benjamin S. Meyers\t#")
	print("# \t\t\tben@lionlogic.org\t#")
	print("#################################################")
	print("\n")

def display_usage_message():
	print("COMMAND\t\tARG\t\tDESCRIPTION")
	print("translate\ttext\t\tTranslate the text to ARPABET and IPA.")
	print("upgrade\t\tcmudict\t\tUpgrade to the most recent cmudict.")

def run_command(args):
	command = args[1]
	print(command)
	print(args)
	if command not in commands.keys():
		sys.exit("WARNING: Invalid command. Try '--help' for details.")
	elif len(args) == 2:
		print(commands[command]())
	elif len(args) == 3: # phonta <command> <option(s)>
		print(commands[command](args[2]))

def main():
	#TODO: Handle translation when term is not in the cmudict.
	#TODO: Handle adding new terms to the cmudict.
	args = sys.argv
	if "python" in args:
		args.remove("python")

	if len(args) < 2:
		display_help_message()
	elif len(args) == 2 and args[1] == "--help":
		display_help_message()
	elif len(args) == 2 and args[1] == "--usage":
		display_usage_message()
	elif len(args) == 2 and args[1] == "--info":
		display_info_message()
	else:
		run_command(args)

if __name__ == "__main__":
	main()
